### PR TITLE
Reformulate

### PR DESCRIPTION
**Pull request by Muennighoff**
Was using the plugin and found a couple words to be confusing~

### CODE REVIEW

**Review by AlexandreAbraham — APPROVED** [review]

**Comment by AlexandreAbraham** [comment]
Looks good, thanks ! May I ask you what you are using this plugin for?

**Comment by Muennighoff** [comment]
Sure, I was labelling images for a client project - Btw I couldnt figure out how to go back to previously labelled images in the dashboad - Is there an obvious way to do it?

**Comment by HenriChabert** [comment]
Hello @Muennighoff,
On the right panel of the webapp, you should have a "BACK" arrow don't you ?

**Comment by AlexandreAbraham** [comment]
I already answered this issue in private. The problem was that one labeler is only able to explore its own history.

**Pull request merged**
